"""
A set of configurations WITHOUT dynamics, i.e. almost free.

The measurement that led to this: labeling was interleaved with molecular dynamics, and
dynamics is sequential by construction; every step needs the force at the previous point,
and it cannot be batched. Because of this, the expensive teacher was called one frame at a
time, and on a cloud GPU this gave 22-92 atom-calcs per second against 460 on the CPU: the
GPU sat idle.

The decoupling is simple: configurations are generated by random sampling (shifts,
rotations, densities), which costs microseconds, while the teacher labels them in a
BATCH. Published datasets for neural-network potentials are built this way for the same
reason: the cost of a dataset is the cost of labeling, not the cost of geometry.

What this approach does NOT give, and this needs to be known: random sampling does not
reproduce the distribution that the system actually walks through at a given temperature.
So the dataset still keeps dynamics slices, but their share is small, while coverage of
the space is provided by the random part. The correct check is the error on frames FROM
DYNAMICS, held out separately: if the model is only good on random configurations, this
shows up immediately.
"""
from __future__ import annotations

import numpy as np

from engine.state import from_symbols

WATER = np.array([[0.0, 0.0, 0.0], [0.0, -0.7575, 0.5865], [0.0, 0.7575, 0.5865]])


def _rotation(rng: np.random.Generator) -> np.ndarray:
    """A random rotation via a quaternion: uniform over the rotation group."""
    q = rng.normal(size=4)
    q /= np.linalg.norm(q)
    w, x, y, z = q
    return np.array(
        [
            [1 - 2 * (y * y + z * z), 2 * (x * y - w * z), 2 * (x * z + w * y)],
            [2 * (x * y + w * z), 1 - 2 * (x * x + z * z), 2 * (y * z - w * x)],
            [2 * (x * z - w * y), 2 * (y * z + w * x), 1 - 2 * (x * x + y * y)],
        ]
    )


# Distance limits below which a configuration is unphysical. The numbers are not eyeballed:
# the O-H bond in water is 0.958 Å, and compressing it below 0.75 Å already costs a few
# electronvolts; non-bonded pairs closer than 1.4 Å simply do not occur in liquid water. The
# MEASURED cost of not having this check: in a set of 330 frames, 78 (24%) had force above
# 100 eV/Å, and the worst frame reached 1.1e7 eV/Å at a minimum distance of 0.394 Å; in the
# quadratic loss, one such frame weighs as much as a million normal ones, and training went
# to garbage (loss 2.9e15).
MIN_BONDED_A = 0.75
MIN_NONBONDED_A = 1.35


def _too_close(positions: np.ndarray, cell=None, molecule_size: int = 3) -> bool:
    """Whether the configuration has a pair closer than allowed. Intramolecular pairs are judged more leniently."""
    p = np.asarray(positions)
    d = p[:, None, :] - p[None, :, :]
    if cell is not None:
        length = float(cell[0, 0])
        d -= length * np.round(d / length)
    r = np.linalg.norm(d, axis=2)
    np.fill_diagonal(r, np.inf)
    n = len(p)
    same_molecule = (np.arange(n)[:, None] // molecule_size) == (np.arange(n)[None, :] // molecule_size)
    if (r[same_molecule] < MIN_BONDED_A).any():
        return True
    return bool((r[~same_molecule] < MIN_NONBONDED_A).any())


def rattled_monomers(rng: np.random.Generator, count: int, max_rattle: float = 0.12):
    """
    Monomers with random distortion: cover bond stretching and angle change.

    The distortion range was reduced from 0.25 to 0.12 Å based on measurement: at 0.25 the
    O-H bond went below 0.7 Å, i.e. into a region where energy grows by orders of
    magnitude and the frame becomes an outlier.
    """
    out = []
    while len(out) < count:
        scale = float(rng.uniform(0.02, max_rattle))
        pos = WATER + rng.normal(scale=scale, size=WATER.shape)
        if not _too_close(pos):
            out.append(from_symbols(["O", "H", "H"], pos))
    return out


def dimers(rng: np.random.Generator, count: int, r_range=(2.2, 6.0), rattle: float = 0.08):
    """
    Dimers at all hydrogen-bond distances and in all mutual orientations.

    The lower bound of 2.2 Å is deliberately chosen well BELOW the equilibrium O-O
    distance (2.98 Å): the model must know repulsion, otherwise in dynamics molecules that
    have come close will collapse into each other; this is the most common cause of a
    neural-network potential's breakdown.
    """
    out = []
    attempts = 0
    while len(out) < count and attempts < count * 50:
        attempts += 1
        sep = float(rng.uniform(*r_range))
        a = (WATER - WATER[0]) @ _rotation(rng).T + rng.normal(scale=rattle, size=WATER.shape)
        b = (WATER - WATER[0]) @ _rotation(rng).T + np.array([sep, 0.0, 0.0]) \
            + rng.normal(scale=rattle, size=WATER.shape)
        pos = np.vstack([a, b])
        if not _too_close(pos):
            out.append(from_symbols(["O", "H", "H"] * 2, pos))
    return out


def clusters(
    rng: np.random.Generator,
    count: int,
    sizes=(4, 8, 16, 32),
    densities=(0.020, 0.0334, 0.045),
    rattle: float = 0.12,
    min_oo: float = 2.1,
):
    """
    Clusters in a periodic cell at various densities, from sparse to compressed.

    `min_oo` is a safeguard against unphysical starts: if two oxygens end up closer than
    this, the frame is discarded. Without it, the dataset picks up configurations with
    energies of tens of eV, and the least-squares fit spends all its capacity reproducing
    them (one such point weighs as much as a hundred normal ones).
    """
    out = []
    attempts = 0
    while len(out) < count and attempts < count * 20:
        attempts += 1
        n_mol = int(rng.choice(sizes))
        density = float(rng.choice(densities))
        box = (n_mol / density) ** (1 / 3)
        side = int(np.ceil(n_mol ** (1 / 3)))
        step = box / side
        positions, placed = [], 0
        for a in range(side):
            for b in range(side):
                for c in range(side):
                    if placed >= n_mol:
                        break
                    centre = (np.array([a, b, c]) + 0.5) * step + rng.normal(scale=rattle * 2, size=3)
                    mol = (WATER - WATER[0]) @ _rotation(rng).T + centre
                    mol += rng.normal(scale=rattle, size=mol.shape)
                    positions.append(mol)
                    placed += 1
        pos = np.vstack(positions)
        # checking ALL pairs, not just oxygen ones: measurement showed that hydrogens got
        # as close as 0.394 Å while the oxygens were intact, and it was exactly these
        # frames that poisoned training
        if _too_close(pos, cell=np.eye(3) * box):
            continue
        oxygens = pos[::3]
        d = oxygens[:, None, :] - oxygens[None, :, :]
        d -= box * np.round(d / box)
        r = np.linalg.norm(d, axis=2)
        np.fill_diagonal(r, np.inf)
        if r.min() < min_oo:
            continue
        out.append(
            from_symbols(["O", "H", "H"] * n_mol, pos, cell=np.eye(3) * box, pbc=(True, True, True))
        )
    return out


MAX_FORCE_EV_PER_A = 50.0


def filter_outliers(frames, max_force=MAX_FORCE_EV_PER_A):
    """
    Force-based filtering AFTER labeling: the second line of defense after the geometric one.

    Threshold 50 eV/Å: at 300-1000 K, forces in water rarely exceed 20 eV/Å, so everything
    above that is not a rare configuration but an unphysical one. The number of dropped
    frames MUST be printed: silently discarding a quarter of the dataset would look like
    successful training.
    """
    kept, dropped = [], []
    for fr in frames:
        if np.abs(fr["forces"]).max() > max_force:
            dropped.append(fr)
        else:
            kept.append(fr)
    return kept, dropped


def build_sampled_states(rng: np.random.Generator, n_monomers=800, n_dimers=1200, n_clusters=3000):
    """A full set of configurations in one call. Cost is seconds, not hours."""
    states = rattled_monomers(rng, n_monomers)
    states += dimers(rng, n_dimers)
    states += clusters(rng, n_clusters)
    rng.shuffle(states)
    return states
